
services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--save", "", "--appendonly", "yes"]
    # --bind 0.0.0.0     => เปิดรับทุก IP
    # --save ""           => ปิด snapshot (RDB)
    # --appendonly yes     => เปิด AOF (append-only file)
    volumes:
      - ./data/redis:/data
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - ./data/influxdb:/var/lib/influxdb
      - ./influxdb-init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped

  k6:
    image: grafana/k6:latest
    container_name: k6
    depends_on:
      - influxdb
    volumes:
      - ./scripts:/scripts
    environment:
      # ใส่ credentials ใน URL สำหรับ InfluxDB v1
      - K6_OUT=influxdb=http://admin:admin123@influxdb:8086
      - K6_INFLUXDB_DB=k6
    restart: "no"
